version: "3.1"

services:
  filebeat:
    build: ./docker/filebeat
    container_name: filebeat
    labels:
      co.elastic.logs/enabled: false
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    labels:
      co.elastic.logs/enabled: false
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    healthcheck:
      test: [ "CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health" ]
      interval: 3s
      timeout: 3s
      retries: 80

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    labels:
      co.elastic.logs/enabled: false
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 80
    depends_on:
      - elasticsearch
