version: '3.1'

services:
  query-api:
    container_name: query-api
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=queryapi@123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/queryapi.pfx
      - ConnectionStrings__MongoDb=mongodb://root:root@mongo:27017/BANK_TRANSACTIONS
    volumes:
      - ~/.aspnet/https/:/https/
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=BANK_TRANSACTIONS
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok'"
      interval: 5s
      timeout: 5s
      retries: 3
